### ISSUE TITLE
any-token issues

### ISSUE THREAD

**Issue by Zergity** [derivable-labs/exposure-comp#73]
Some issue after the any-token feature

**Comment by Zergity** [comment]
1. switching network

STEPS:
* select an ERC20 as input token
* change the network
* see the input token logo

![Image](https://github.com/derivable-labs/exposure-comp/assets/37166829/83f6f061-0d17-4de5-b8fb-06537eef691b)

**Comment by Zergity** [comment]
2/ FuncPlot wrong value input to `setDr`

![Image](https://github.com/derivable-labs/exposure-comp/assets/37166829/7276153b-0a48-4112-bada-454b78399e1e)

```
  useEffect(() => {
    switch (tradeType) {
      case TRADE_TYPE.LONG:
        setDr(Number(amountIn), 0, 0)
        break
      case TRADE_TYPE.SHORT:
        setDr(0, Number(amountIn), 0)
        break
      case TRADE_TYPE.LIQUIDITY:
        setDr(0, 0, Number(amountIn))
        break
      default:
        setDr(0, 0, 0)
    }
  }, [amountIn, tradeType])
```

**Comment by athevinha** [comment]
https://github.com/derivable-labs/exposure-comp/tree/fix/input
